Update README.md
gardener/external-dns-management pull request #120
Opened 2020-09-09 12:34 UTC by BeckerMax

@mandelsoft Did I understand the `--ttl` correctly? If yes, we could merge this to help future readers to understand what this ttl does in comparison to the other ttl options configurable.

2020-09-14 06:11 UTC, MartinWeindel requested changes
Please update description in the code, too.
See https://github.com/gardener/external-dns-management/blob/8122ea919075f4045636a3858e19d8cd91395263/pkg/dns/provider/controller.go#L120

2020-09-16 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/external-dns-management?pullRequest=120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/external-dns-management?pullRequest=120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/external-dns-management?pullRequest=120) it.</sub>

2020-12-23 21:39 UTC, BeckerMax commented
/help

2020-12-23 21:42 UTC, BeckerMax commented
sorry for the delay. Can you have another look @MartinWeindel

2020-12-28 08:05 UTC, mandelsoft approved these changes

2020-12-28 08:05 UTC, merged