Adds Artifacts for Landscaper Integration
gardener/external-dns-management pull request #164
Opened 2021-04-01 08:46 UTC by jschicktanz

**What this PR does / why we need it**:
Adds artifacts for Landscaper integration. Pipeline now produces a CTF that contains the Component Descriptor, Blueprint, and Helm Chart (as Blobs) for this component.

Co-authored by @enrico-kaack-comp 

**Which issue(s) this PR fixes**:
https://github.com/gardener/landscapercli/issues/64

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2021-04-01 08:48 UTC, jschicktanz commented
@schrodit

2021-04-12 15:52 UTC, MartinWeindel reviewed
Uwe and I have some suggestions

2021-04-12 15:52 UTC, MartinWeindel commented on .landscaper/blueprint/deploy-executions.yaml
> +            type: cloudflare-dns
```suggestion
            type: cloudflare-dns
          - kind: DNSProvider
            type: infoblox-dns
          - kind: DNSProvider
            type: netlify-dns            
```

2021-04-12 15:52 UTC, MartinWeindel commented on .landscaper/blueprint/deploy-executions.yaml
> +            type: cloudflare-dns
add missing DNS provider types

2021-04-12 15:52 UTC, MartinWeindel commented on .landscaper/resources.yaml
> +name: dns-controller-manager-blueprint
```suggestion
name: dns-controller-manager-controller-registration
```

2021-04-22 11:41 UTC, jschicktanz commented
Hi, thank you for your review. We have included your feedback and additionally made 1 small change which makes the chart values in the blueprint optional (for enabling the installation with just the default values).

2021-06-04 15:26 UTC, jschicktanz commented
/invite @schrodit

2021-06-21 09:29 UTC, schrodit requested changes

2021-06-21 09:29 UTC, schrodit commented on .landscaper/resources.yaml
> +  mediaType: "application/vnd.gardener.landscaper.blueprint.v1+tar+gzip"
```suggestion
  mediaType: "application/vnd.gardener.landscaper.blueprint.v1.tar+gzip"
```

2021-06-21 09:29 UTC, schrodit commented on .landscaper/resources.yaml
> +  compress: true
add preserveDir

2021-06-21 09:58 UTC, schrodit approved these changes

2021-06-21 10:30 UTC, merged